### PR TITLE
AllTalk TTS Update

### PR DESCRIPTION
**Pull request by erew123**
I didn't know about your project, someone had a problem so I've made a small update for you:

Here's a summary of the changes for the Pull Request:

- **Version Support**
  - Added support for both AllTalk V1 and V2 servers
  - Automatic URL handling for different version responses (V1: full URL, V2: relative path)

- **Voice Selection**
  - Standard voice selection dropdown with server-fetched voices
  - Voice preview functionality
  - Persistent voice settings stored in local storage

- **RVC Integration (AllTalk V2)**
  - RVC voice selection with fetched available voices
  - RVC pitch control (-24 to +24)
  - RVC settings automatically disabled for V1 servers
  - Defaults to 'Disabled' for RVC voice and '0' for pitch

- **Server Configuration**
  - Server URL configuration with validation
  - Server status monitoring
  - Automatic reconnection and voice list refresh
  - Version selection (V1/V2)

- **UI Improvements**
  - Clean, consistent interface matching existing design
  - Language selection dropdown
  - Status indicators for server connection
  - Loading states and error handling
  - Documentation link to AllTalk Wiki

- **Settings Persistence**
  - Settings saved in local storage
  - Settings restored on page reload
  - Independent settings for V1/V2 configurations

- **Error Handling**
  - Comprehensive error reporting
  - Server connection validation
  - Fallback handling for unavailable features

image

Thanks

### CODE REVIEW

**Comment by erew123** [comment]
Oh, I forgot to mention. This now plays audio in the web-browser and no longer using the AllTalk terminal/command prompt, so that should be better generally.

**Comment by slowsynapse** [comment]
Thank you, I was away on business. Much appreciated, will review. :))

**Comment by slowsynapse** [comment]
Currently, can't get it to run on Mac OS X, some dependency issue ("TTS" and "sudachipy"), trying to diagnose.

**Comment by erew123** [comment]
Hi @slowsynapse Sorry its taken a while to get back to you, Im mid releasing AllTalk v2 the other day and its crazy busy. Do you mean youre installing AllTalk on a mac? or the extension is having an issue on mac?

With AllTalk on mac, Im a bit shaky on that as Ive never had a mac to test it and Ive put up the gauntlet to someone to get it working and Ill try help as/where I can. If it is specially just getting a copy of AllTalk for testing though, you can use a free Google Colab.

My Wiki Page on it is here https://github.com/erew123/alltalk_tts/wiki/Google-COLAB

But you can go to this link: https://colab.research.google.com/github/erew123/alltalk_tts/blob/alltalkbeta/googlecolab.ipynb and sign into your google account.

Then it should automatically set a T4 server type (top right) and:

image

and once you are past Step 2 you should get this:

image

Its the API address you would want with Amica, though it will only have set up 1x voice at this point in time, on Piper TTS, to download other voices/TTS models etc you would have to go into the AllTalk Gradio interface (the links below the API) and get to know AllTalk a bit. If you want to go that far, you can either look around the help in the interface or look on the AllTalk Wiki quick start. https://github.com/erew123/alltalk_tts/wiki/AllTalk-V2-QuickStart-Guide

Give me a shout if you need.

Thanks

**Comment by slowsynapse** [comment]
hey @erew123 , we identified the issue and its a slight syntax issue, will be sending update soon. We got it working too, it's super cool.

**Comment by slowsynapse** [comment]
[
2024-11-29 12 15 54 AM
2024-11-29 12 16 03 AM
](url)

^ Here is what needs fixing (in comments), Line 25 and Line 81

**Comment by erew123** [comment]
@slowsynapse Ill take that as a win (just the 2x lines wrong). So busy with everything else and I knocked this together kind of quick (if Im honest). Should be updated as you specified. Thanks for debugging, saved me a hell of a task there!!

**Pull request merged**
