### PR TITLE
Wake word issue 55

### PR DESCRIPTION
**Pull request by danyyil-pelekhatyi**
Added support for a wake word

### CODE REVIEW

**Comment by slowsynapse** [comment]
Got it Danyyil. Thanks. Will merge in a bit after 1 more test.

**Comment by slowsynapse** [comment]
Can't get wake word to save on Vercel.

**Comment by slowsynapse** [comment]
Requires capitalization fixes. E.g. Wake word Settings > Wake Word Settings. Screenshot attached.
Screenshot from 2024-04-08 06-09-14

**Comment by danyyil-pelekhatyi** [comment]
Capitalization fixes done.

**Comment by slowsynapse** [comment]
Merged. Thank you.

**Pull request merged**
